[project]
name = "demoEventSite"
version = "1.0.0"
description = "Demo static flask-based website"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"